os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: Pd2+8QG7cFUew2DyBdElcoRFCFdx8vKmSHHFKaJnN3mfRWEPgkQzYz8lblhPAAJwYb5J1aHeKDiQd4F8QOZ839n7XAnDdSJMT51SQF5Icp17oIZp2Bg6JBBvs0/FDq/ZVBokUh0of14xJZm3KGev4zETVGSTQqz3SE6s+CRnMgj7FLXhQYaZIc4LcuECfGe2KenJ+5WSJZePjuC66dNOf48wdY3laF8NW/C+TMcELXTumXYTJKwdKStmSqzZevCi5dnZnk8fKrayy/dwT5JamA91arHDtx4JzlSCMm2OG7vzm78NyLKYRzRamhzo9RVPOTssy/7RM09fPq1pv561aINXW9u06rYgT7J+XJs35cSsBn+Fr7nYIDulxvOm8HfRFc2N/xiM68pqhPcUpe0AM4t682EHvqRCmOLMWwvLto3Dn+igzB133pnc7BtlaAOJr+hEXM/snTYKsY+TEhlOwkDcVJUUJSG+MI3GD0WVezuBNhWsGaNczZDelkU0FaxsC8wkU/+yAUngURcLJr7On1AXh2cJvAy7TwMhki51dzGLHjeGw54y2Ebtnm5KZd/gT/fCRRa23jHi7YWlcYONii8vzevvMPYu4+oBdzEbXn5JEaMX5kGlivVKAArOAOONBitrYaGX/7iUQlwWU9HB6/SE2Fu3etsPWZhaxle1vm0=
